locs = {
    'Azalea Town Gym Badge': 0 ,
    'Behind Slowpoke Well Hidden': 0 ,
    'Bike Shop': 0 ,
    'Blackthorn City Gym Badge': 0 ,
    'Buena Item': 0 ,
    'Bugsy TM': 0 ,
    'Burned Tower Hidden Ether': 0 ,
    'Burned Tower Hidden Ultra Ball': 0 ,
    'Burned Tower Rock Smash Item': 0 ,
    'Burned Tower Strength Item': 0 ,
    'Celadon City Gym Badge': 0 ,
    'Celadon City Hidden PP Up': 0 ,
    'Cerulean City Gym Badge': 0 ,
    'Cerulean City Hidden Berserk Gene': 0 ,
    'Charcoal Kiln': 0 ,
    'Chuck TM': 0 ,
    'Cianwood City Gym Badge': 0 ,
    'Cianwood City Hidden Max Ether': 0 ,
    'Cianwood City Hidden Revive': 0 ,
    'Cianwood Fly HM': 0 ,
    'Cinnabar Island': 0 ,
    'Cinnabar Island Gym Badge': 0 ,
    'Cinnabar Island Hidden Rare Candy': 0 ,
    'Clair TM': 0 ,
    'Coin Case Underground': 0 ,
    'Copycat Rail Pass': 0 ,
    'Dance Theatre Surf HM': 0 ,
    'Dark Cave Black Glasses': 0 ,
    'Dark Cave Blackthorn Revive': 0 ,
    'Dark Cave Snore TM': 0 ,
    'Dark Cave Violet Dire Hit': 0 ,
    'Dark Cave Violet Full Heal': 0 ,
    'Dark Cave Violet Hidden Elixer': 0 ,
    'Dark Cave Violet Hyper Potion': 0 ,
    'Dark Cave Violet Potion': 0 ,
    'Department Store Basement 1': 0 ,
    'Department Store Basement 2': 0 ,
    'Department Store Basement 3': 0 ,
    'Department Store Basement 4 Underground': 0 ,
    'Diglett\'s Cave Hidden Max Revive': 0 ,
    'Dojo Band': 0 ,
    'Dragons Den Calcium': 0 ,
    'Dragons Den Dragon Fang': 0 ,
    'Dragons Den Hidden Max Elixer': 0 ,
    'Dragons Den Hidden Max Potion': 0 ,
    'Dragons Den Hidden Revive': 0 ,
    'Dragons Den Max Elixer': 0 ,
    'Ecruteak City Gym Badge': 0 ,
    'Ecruteak City Hidden Hyper Potion': 0 ,
    'Elm Aide Pokeballs': 0 ,
    'Elm Aide Potion': 0 ,
    'Elm Master Ball': 0 ,
    'Elm SS Ticket': 0 ,
    'Erika TM': 0 ,
    'Expansion Card Gift': 0 ,
    'Falkner TM': 0 ,
    'Flower Shop': 0 ,
    'Fuchsia City Gym Badge': 0 ,
    'Goldenrod City Gym': 0 ,
    'Goldenrod Tunnel Full Heal': 0 ,
    'Goldenrod Tunnel Hidden Max Potion': 0 ,
    'Goldenrod Tunnel Hidden Revive': 0 ,
    'Goldenrod Tunnel Max Ether': 0 ,
    'Goldenrod Tunnel Rocket Attack': 0 ,
    'Goldenrod Tunnel Sleep Talk TM': 0 ,
    'Goldenrod Tunnel Smoke Ball': 0 ,
    'Goldenrod Tunnel Ultra Ball': 0 ,
    'Goldenrod Underground Hidden Antidote': 0 ,
    'Goldenrod Underground Hidden Paralyze Heal': 0 ,
    'Goldenrod Underground Hidden Super Potion': 0 ,
    'Good Rod Guru': 0 ,
    'Headbutt Guy': 0 ,
    'Hidden Machine Part': 0 ,
    'Ice Path Full Heal': 0 ,
    'Ice Path Hidden Carbos': 0 ,
    'Ice Path Hidden Ice Heal': 0 ,
    'Ice Path Hidden Max Potion': 0 ,
    'Ice Path Iron': 0 ,
    'Ice Path Max Potion': 0 ,
    'Ice Path Nevermeltice': 0 ,
    'Ice Path PP Up': 0 ,
    'Ice Path Protein': 0 ,
    'Ice Path Rest TM': 0 ,
    'Ice Path Waterfall HM': 0 ,
    'Ilex Cut HM': 0 ,
    'Ilex Forest Antidote': 0 ,
    'Ilex Forest Ether': 0 ,
    'Ilex Forest Hidden Ether': 0 ,
    'Ilex Forest Hidden Full Heal': 0 ,
    'Ilex Forest Hidden Super Potion': 0 ,
    'Ilex Forest Revive': 0 ,
    'Ilex Forest X Attack': 0 ,
    'Itemfinder House': 0 ,
    'Janine TM': 0 ,
    'Jasmine TM': 0 ,
    'Kenya Gate Item': 0 ,
    'King\'s Rock Guy': 0 ,
    'Kurt\'s Lure Ball': 0 ,
    'Lake of Rage Detect TM': 0 ,
    'Lake Of Rage Elixer': 0 ,
    'Lake of Rage Hidden Full Restore': 0 ,
    'Lake of Rage Hidden Max Potion': 0 ,
    'Lake of Rage Hidden Power TM': 0 ,
    'Lighthouse Ether': 0 ,
    'Lighthouse Hidden Hyper Potion': 0 ,
    'Lighthouse Rare Candy': 0 ,
    'Lighthouse Super Potion': 0 ,
    'Lighthouse Super Repel': 0 ,
    'Lighthouse Swagger TM': 0 ,
    'Mahogany Town Gym Badge': 0 ,
    'Miracle Seed Man': 0 ,
    'Morty TM': 0 ,
    'Mr Psychic TM': 0 ,
    'Mr. Pokemon\'s Egg': 0 ,
    'Mr. Pokemon\'s EXP Share': 0 ,
    'Mt Mortar Carbos': 0 ,
    'Mt Mortar Defense Curl TM': 0 ,
    'Mt Mortar Dragon Scale': 0 ,
    'Mt Mortar Elixer': 0 ,
    'Mt Mortar Ether': 0 ,
    'Mt Mortar Full Restore': 0 ,
    'Mt Mortar Hidden Full Restore': 0 ,
    'Mt Mortar Hidden Hyper Potion': 0 ,
    'Mt Mortar Hidden Max Repel': 0 ,
    'Mt Mortar Hidden Max Revive': 0 ,
    'Mt Mortar Inner Escape Rope': 0 ,
    'Mt Mortar Inner Hyper Potion': 0 ,
    'Mt Mortar Iron': 0 ,
    'Mt Mortar Lower Hyper Potion': 0 ,
    'Mt Mortar Max Ether': 0 ,
    'Mt Mortar Max Potion': 0 ,
    'Mt Mortar Max Potion Number 2': 0 ,
    'Mt Mortar Max Revive': 0 ,
    'Mt Mortar Nugget': 0 ,
    'Mt Mortar PP Up': 0 ,
    'Mt Mortar Rare Candy': 0 ,
    'Mt Mortar Revive': 0 ,
    'Mt Mortar Ultra Ball': 0 ,
    'Mt Mortar Upper Escape Rope': 0 ,
    'Mt. Silver Calcium': 0 ,
    'Mt. Silver Escape Rope': 0 ,
    'Mt. Silver Full Restore': 0 ,
    'Mt. Silver Hidden Dire Hit': 0 ,
    'Mt. Silver Hidden Max Potion': 0 ,
    'Mt. Silver Hidden Ultra Ball': 0 ,
    'Mt. Silver Max Elixer': 0 ,
    'Mt. Silver Max Protein': 0 ,
    'Mt. Silver Max Revive': 0 ,
    'Mt. Silver 2F Ultra Ball': 0 ,
    'Mt. Silver Outside Hidden Full Restore': 0 ,
    'Mt. Silver PP UP': 0 ,
    'Mt. Silver 1F Ultra Ball': 0 ,
    'Mystic Water Man': 0 ,
    'National Park Dig TM': 0 ,
    'National Park Parlyz Heal': 0 ,
    'National Park Quick Claw': 0 ,
    'Oak Pokedex': 0 ,
    'Old Rod Guru': 0 ,
    'Olivine City Gym Badge': 0 ,
    'Olivine Port Hidden Protein': 0 ,
    'Olivine Strength HM': 0 ,
    'Pewter City Gym Badge': 0 ,
    'Pink Bow': 0 ,
    'Pokegear Gift': 0 ,
    'Power Plant Activated': 0 ,
    'Pryce TM': 0 ,
    'Radio Card Quiz': 0 ,
    'Radio Tower Rockets Part 1': 0 ,
    'Radio Tower Rockets Part 2': 0 ,
    'Radio Tower Sunny Day TM': 0 ,
    'Radio Tower Ultra Ball': 0 ,
    'Rainbow Wing Gift': 0 ,
    'Red Scale Dropped': 0 ,
    'Rock Smash Guy': 0 ,
    'Rock Tunnel Elixer': 0 ,
    'Rock Tunnel Hidden Max Potion': 0 ,
    'Rock Tunnel Hidden X Accuracy': 0 ,
    'Rock Tunnel Hidden X Defend': 0 ,
    'Rock Tunnel Iron': 0 ,
    'Rock Tunnel PP UP': 0 ,
    'Rock Tunnel Revive': 0 ,
    'Rock Tunnel Steel Wing TM': 0 ,
    'Rocket Base 1F Guard Spec': 0 ,
    'Rocket Base 1F Hyper Potion': 0 ,
    'Rocket Base 1F Nugget': 0 ,
    'Rocket Base 2F Thief TM': 0 ,
    'Rocket Base 3F Full Heal': 0 ,
    'Rocket Base 3F Ice Heal': 0 ,
    'Rocket Base 3F Protein': 0 ,
    'Rocket Base 3F Ultra Ball': 0 ,
    'Rocket Base 3F X Special': 0 ,
    'Rocket Base Hidden Full Heal': 0 ,
    'Rocket Base Hidden Revive': 0 ,
    'Rocket Base Whirlpool HM': 0 ,
    'Route 11 Hidden Revive': 0 ,
    'Route 12 Calcium': 0 ,
    'Route 12 Hidden Elixer': 0 ,
    'Route 12 Nugget': 0 ,
    'Route 13 Hidden Calcium': 0 ,
    'Route 15 PP Up': 0 ,
    'Route 17 Hidden Max Elixer': 0 ,
    'Route 17 Hidden Max Ether': 0 ,
    'Route 2 Carbos': 0 ,
    'Route 2 Dire Hit': 0 ,
    'Route 2 Elixer': 0 ,
    'Route 2 Hidden Full Heal': 0 ,
    'Route 2 Hidden Full Restore': 0 ,
    'Route 2 Hidden Max Ether': 0 ,
    'Route 2 Hidden Revive': 0 ,
    'Route 2 Max Potion': 0 ,
    'Route 2 Nugget House': 0 ,
    'Route 25 Hidden Potion': 0 ,
    'Route 25 Nugget': 0 ,
    'Route 25 Protein': 0 ,
    'Route 26 Max Elixer': 0 ,
    'Route 27 Rare Candy': 0 ,
    'Route 27 Solar Beam TM': 0 ,
    'Route 28 Hidden Rare Candy': 0 ,
    'Route 28 Steel Wing TM': 0 ,
    'Route 29 Potion': 0 ,
    'Route 30 Antidote': 0 ,
    'Route 30 Berry Man': 0 ,
    'Route 30 Hidden Potion': 0 ,
    'Route 31 Kenya Item': 0 ,
    'Route 31 Pokeball': 0 ,
    'Route 31 Potion': 0 ,
    'Route 32 Great Ball': 0 ,
    'Route 32 Hidden Super Potion': 0 ,
    'Route 32 Repel': 0 ,
    'Route 32 Roar Dude': 0 ,
    'Route 34 Hidden Rare Candy': 0 ,
    'Route 34 Hidden Super Potion': 0 ,
    'Route 34 Nugget': 0 ,
    'Route 35 Rollout TM': 0 ,
    'Route 37 Hidden Ether': 0 ,
    'Route 39 Hidden Nugget': 0 ,
    'Route 4 Hidden Ultra Ball': 0 ,
    'Route 4 HP UP': 0 ,
    'Route 40 Hidden Hyper Potion': 0 ,
    'Route 41 Hidden Max Ether': 0 ,
    'Route 42 Hidden Max Potion': 0 ,
    'Route 42 Middle Island Super Potion': 0 ,
    'Route 42 Ultra Ball': 0 ,
    'Route 43 Max Ether': 0 ,
    'Route 43 Sludge Bomb TM': 0 ,
    'Route 44 Hidden Elixer': 0 ,
    'Route 44 Max Repel': 0 ,
    'Route 44 Max Revive': 0 ,
    'Route 44 Ultra Ball': 0 ,
    'Route 45 Elixer': 0 ,
    'Route 45 Hidden PP Up': 0 ,
    'Route 45 Max Potion': 0 ,
    'Route 45 Nugget': 0 ,
    'Route 45 Revive': 0 ,
    'Route 46 X Speed': 0 ,
    'Route 5 Cleanse Tag': 0 ,
    'Route 9 Hidden Ether': 0 ,
    'Ruins of Alph Ho Oh Chamber 1': 0 ,
    'Ruins of Alph Ho Oh Chamber 2': 0 ,
    'Ruins of Alph Ho Oh Chamber 3': 0 ,
    'Ruins of Alph Ho Oh Chamber 4': 0 ,
    'Ruins of Alph Light Chamber 1': 0 ,
    'Ruins of Alph Light Chamber 2': 0 ,
    'Ruins of Alph Light Chamber 3': 0 ,
    'Ruins of Alph Light Chamber 4': 0 ,
    'Ruins of Alph Rope Chamber 1': 0 ,
    'Ruins of Alph Rope Chamber 2': 0 ,
    'Ruins of Alph Rope Chamber 3': 0 ,
    'Ruins of Alph Rope Chamber 4': 0 ,
    'Ruins of Alph Water Chamber 1': 0 ,
    'Ruins of Alph Water Chamber 2': 0 ,
    'Ruins of Alph Water Chamber 3': 0 ,
    'Ruins of Alph Water Chamber 4': 0 ,
    'Saffron City Gym Badge': 0 ,
    'Secret Potion Man': 0 ,
    'Silph Co Upgrade': 0 ,
    'Silver Wing Old Man': 0 ,
    'Slowpoke Well Floor 1 Super Potion': 0 ,
    'Slowpoke Well Rain Dance TM': 0 ,
    'Soft Sand Girls': 0 ,
    'Sprout Tower Escape Rope': 0 ,
    'Sprout Tower Flash HM': 0 ,
    'Sprout Tower Parlyz Heal': 0 ,
    'Sprout Tower Potion': 0 ,
    'Sprout Tower X Accuracy': 0 ,
    'SS Aqua': 0 ,
    'Super Rod Guru': 0 ,
    'Sweet Scent Girl': 0 ,
    'Tin Tower Escape Rope': 0 ,
    'Tin Tower Full Heal': 0 ,
    'Tin Tower Full Restore': 0 ,
    'Tin Tower Hidden Carbos': 0 ,
    'Tin Tower Hidden Full Restore': 0 ,
    'Tin Tower Hidden Max Potion': 0 ,
    'Tin Tower HP Up': 0 ,
    'Tin Tower Max Elixer': 0 ,
    'Tin Tower Max Potion': 0 ,
    'Tin Tower Max Revive': 0 ,
    'Tin Tower Nugget': 0 ,
    'Tin Tower PP Up': 0 ,
    'Tin Tower Rare Candy': 0 ,
    'Tin Tower Ultra Ball': 0 ,
    'Tohjo Falls Moon Stone': 0 ,
    'Underground Path Hidden Full Restore': 0 ,
    'Underground Path Hidden X Special': 0 ,
    'Union Cave Floor 1 Awakening': 0 ,
    'Union Cave Floor 1 Great Ball': 0 ,
    'Union Cave Floor 1 Potion': 0 ,
    'Union Cave Floor 1 X Attack': 0 ,
    'Union Cave Floor 2 X Defend': 0 ,
    'Union Cave Floor 3 Elixir': 0 ,
    'Union Cave Floor 3 Hyper Potion': 0 ,
    'Union Cave Swift TM': 0 ,
    'Vermilion City Fan Club President': 0 ,
    'Vermilion City Gym Badge': 0 ,
    'Vermilion City Hidden Full Heal': 0 ,
    'Vermilion City Lost Item': 0 ,
    'Vermilion Port Hidden Iron': 0 ,
    'Victory Road Earthquake TM': 0 ,
    'Victory Road Full Heal': 0 ,
    'Victory Road Full Restore': 0 ,
    'Victory Road Hidden Full Heal': 0 ,
    'Victory Road Hidden Max Potion': 0 ,
    'Victory Road HP Up': 0 ,
    'Victory Road Max Revive': 0 ,
    'Violet City Gym Badge': 0 ,
    'Violet City Hidden Hyper Potion': 0 ,
    'Violet City PP UP': 0 ,
    'Violet City Rare Candy': 0 ,
    'Viridian City Gym Badge': 0 ,
    'Viridian Dream Eater TM': 0 ,
    'Whirl Islands B1 Full Restore': 0 ,
    'Whirl Islands B2 Full Restore': 0 ,
    'Whirl Islands B2 Max Elixer': 0 ,
    'Whirl Islands B2 Max Revive': 0 ,
    'Whirl Islands Calcium': 0 ,
    'Whirl Islands Carbos': 0 ,
    'Whirl Islands Escape Rope': 0 ,
    'Whirl Islands Hidden Full Restore': 0 ,
    'Whirl Islands Hidden Rare Candy': 0 ,
    'Whirl Islands Hidden Ultra Ball': 0 ,
    'Whirl Islands NE Ultra Ball': 0 ,
    'Whirl Islands Nugget': 0 ,
    'Whirl Islands SW Ultra Ball': 0 ,
    'Whitney TM': 0
}
