# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTGUIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 442)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TrainerLevelScaling = QtWidgets.QCheckBox(self.centralwidget)
        self.TrainerLevelScaling.setGeometry(QtCore.QRect(20, 80, 131, 17))
        self.TrainerLevelScaling.setObjectName("TrainerLevelScaling")
        self.Randomize = QtWidgets.QPushButton(self.centralwidget)
        self.Randomize.setGeometry(QtCore.QRect(590, 300, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Randomize.setFont(font)
        self.Randomize.setObjectName("Randomize")
        self.SelectRomFile = QtWidgets.QPushButton(self.centralwidget)
        self.SelectRomFile.setGeometry(QtCore.QRect(340, 340, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SelectRomFile.setFont(font)
        self.SelectRomFile.setObjectName("SelectRomFile")
        self.RegularWildLevelScaling = QtWidgets.QCheckBox(self.centralwidget)
        self.RegularWildLevelScaling.setGeometry(QtCore.QRect(20, 126, 91, 41))
        self.RegularWildLevelScaling.setObjectName("RegularWildLevelScaling")
        self.TrainerLevelShiftBonus = QtWidgets.QLineEdit(self.centralwidget)
        self.TrainerLevelShiftBonus.setGeometry(QtCore.QRect(100, 110, 31, 20))
        self.TrainerLevelShiftBonus.setObjectName("TrainerLevelShiftBonus")
        self.TrainerLevelShift = QtWidgets.QLabel(self.centralwidget)
        self.TrainerLevelShift.setGeometry(QtCore.QRect(30, 100, 71, 31))
        self.TrainerLevelShift.setObjectName("TrainerLevelShift")
        self.WildLevelShift = QtWidgets.QLabel(self.centralwidget)
        self.WildLevelShift.setGeometry(QtCore.QRect(30, 195, 71, 31))
        self.WildLevelShift.setObjectName("WildLevelShift")
        self.WildLevelShiftBonus = QtWidgets.QLineEdit(self.centralwidget)
        self.WildLevelShiftBonus.setGeometry(QtCore.QRect(100, 200, 31, 20))
        self.WildLevelShiftBonus.setObjectName("WildLevelShiftBonus")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.ChooseSettings = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseSettings.setGeometry(QtCore.QRect(580, 50, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ChooseSettings.setFont(font)
        self.ChooseSettings.setObjectName("ChooseSettings")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 100, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 150, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.CurentSettings = QtWidgets.QLabel(self.centralwidget)
        self.CurentSettings.setGeometry(QtCore.QRect(560, 130, 231, 20))
        self.CurentSettings.setAlignment(QtCore.Qt.AlignCenter)
        self.CurentSettings.setObjectName("CurentSettings")
        self.SettingsDescription = QtWidgets.QLabel(self.centralwidget)
        self.SettingsDescription.setGeometry(QtCore.QRect(570, 180, 221, 111))
        self.SettingsDescription.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.SettingsDescription.setWordWrap(True)
        self.SettingsDescription.setObjectName("SettingsDescription")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.modifierList = QtWidgets.QListWidget(self.centralwidget)
        self.modifierList.setGeometry(QtCore.QRect(150, 90, 161, 291))
        self.modifierList.setObjectName("modifierList")
        item = QtWidgets.QListWidgetItem()
        self.modifierList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.modifierList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.modifierList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.modifierList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.modifierList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.modifierList.addItem(item)
        self.LoadModifier = QtWidgets.QPushButton(self.centralwidget)
        self.LoadModifier.setGeometry(QtCore.QRect(320, 100, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LoadModifier.setFont(font)
        self.LoadModifier.setObjectName("LoadModifier")
        self.DeleteModifier = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteModifier.setGeometry(QtCore.QRect(320, 170, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DeleteModifier.setFont(font)
        self.DeleteModifier.setObjectName("DeleteModifier")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(380, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.CurrentGoal = QtWidgets.QLabel(self.centralwidget)
        self.CurrentGoal.setGeometry(QtCore.QRect(320, 60, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CurrentGoal.setFont(font)
        self.CurrentGoal.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.CurrentGoal.setObjectName("CurrentGoal")
        self.OutputSpoiler = QtWidgets.QCheckBox(self.centralwidget)
        self.OutputSpoiler.setGeometry(QtCore.QRect(20, 260, 121, 17))
        self.OutputSpoiler.setChecked(True)
        self.OutputSpoiler.setObjectName("OutputSpoiler")
        self.OutputRomName = QtWidgets.QLineEdit(self.centralwidget)
        self.OutputRomName.setGeometry(QtCore.QRect(20, 300, 121, 20))
        self.OutputRomName.setObjectName("OutputRomName")
        self.OutputRomLabel = QtWidgets.QLabel(self.centralwidget)
        self.OutputRomLabel.setGeometry(QtCore.QRect(20, 280, 101, 16))
        self.OutputRomLabel.setObjectName("OutputRomLabel")
        self.ModifierDescription = QtWidgets.QLabel(self.centralwidget)
        self.ModifierDescription.setGeometry(QtCore.QRect(320, 260, 261, 71))
        self.ModifierDescription.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ModifierDescription.setWordWrap(True)
        self.ModifierDescription.setObjectName("ModifierDescription")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(320, 230, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.SaveSettings = QtWidgets.QPushButton(self.centralwidget)
        self.SaveSettings.setGeometry(QtCore.QRect(20, 330, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SaveSettings.setFont(font)
        self.SaveSettings.setObjectName("SaveSettings")
        self.SpecialWildLevelScaling = QtWidgets.QCheckBox(self.centralwidget)
        self.SpecialWildLevelScaling.setGeometry(QtCore.QRect(20, 160, 111, 31))
        self.SpecialWildLevelScaling.setObjectName("SpecialWildLevelScaling")
        self.SeedInput = QtWidgets.QLineEdit(self.centralwidget)
        self.SeedInput.setGeometry(QtCore.QRect(70, 230, 71, 20))
        self.SeedInput.setText("")
        self.SeedInput.setObjectName("SeedInput")
        self.SetSeedLabel = QtWidgets.QLabel(self.centralwidget)
        self.SetSeedLabel.setGeometry(QtCore.QRect(10, 230, 51, 16))
        self.SetSeedLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SetSeedLabel.setObjectName("SetSeedLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TrainerLevelScaling.setText(_translate("MainWindow", "Scale Trainer Levels?"))
        self.Randomize.setText(_translate("MainWindow", "Randomize Rom"))
        self.SelectRomFile.setText(_translate("MainWindow", "Select Rom File"))
        self.RegularWildLevelScaling.setText(_translate("MainWindow", "Scale Regular \n"
"Wild Levels?"))
        self.TrainerLevelShiftBonus.setText(_translate("MainWindow", "0"))
        self.TrainerLevelShift.setText(_translate("MainWindow", "Trainer Level\n"
" Shift Bonus:"))
        self.WildLevelShift.setText(_translate("MainWindow", "Wild Level\n"
" Shift Bonus:"))
        self.WildLevelShiftBonus.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Pokemon Crystal-Speedchoice Item Randomizer Tool"))
        self.label_2.setText(_translate("MainWindow", "Options"))
        self.ChooseSettings.setText(_translate("MainWindow", "Select Logic Settings"))
        self.label_4.setText(_translate("MainWindow", "Curent Settings"))
        self.label_5.setText(_translate("MainWindow", "Settings Description"))
        self.CurentSettings.setText(_translate("MainWindow", "No settings selected!"))
        self.SettingsDescription.setText(_translate("MainWindow", "No settings selected!"))
        self.label_8.setText(_translate("MainWindow", "Modifiers"))
        __sortingEnabled = self.modifierList.isSortingEnabled()
        self.modifierList.setSortingEnabled(False)
        item = self.modifierList.item(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.modifierList.item(1)
        item.setText(_translate("MainWindow", "settings"))
        item = self.modifierList.item(2)
        item.setText(_translate("MainWindow", "have"))
        item = self.modifierList.item(3)
        item.setText(_translate("MainWindow", "been"))
        item = self.modifierList.item(4)
        item.setText(_translate("MainWindow", "loaded!"))
        self.modifierList.setSortingEnabled(__sortingEnabled)
        self.LoadModifier.setText(_translate("MainWindow", "Load New Modifier"))
        self.DeleteModifier.setText(_translate("MainWindow", "Delete Selected Modifier"))
        self.label_9.setText(_translate("MainWindow", "Current Goal"))
        self.CurrentGoal.setText(_translate("MainWindow", "No goal set!"))
        self.OutputSpoiler.setText(_translate("MainWindow", "Output Logic Spoiler?"))
        self.OutputRomName.setText(_translate("MainWindow", "RandomizedRom"))
        self.OutputRomLabel.setText(_translate("MainWindow", "Output Rom Name:"))
        self.ModifierDescription.setText(_translate("MainWindow", "No modifier selected!"))
        self.label_12.setText(_translate("MainWindow", "Selected Modifier Description"))
        self.SaveSettings.setText(_translate("MainWindow", "Save\n"
" Settings"))
        self.SpecialWildLevelScaling.setText(_translate("MainWindow", "Scale Special\n"
"Wild Levels?"))
        self.SetSeedLabel.setText(_translate("MainWindow", "Set Seed:"))
