ItemRandoData::
ItemRandoDataVersion::
	db 1
ItemRandoActive::
.ckir_BEFOREItemRandoActive::
	db
.ckir_AFTERItemRandoActive::
ItemRandoRocketless::
.ckir_BEFOREItemRandoRocketless::
	db
.ckir_AFTERItemRandoRocketless::
ItemRandoEasyClairBadge::
.ckir_BEFOREItemRandoEasyClairBadge::
	db
.ckir_AFTERItemRandoEasyClairBadge::
ItemRandoEarlyKanto::
.ckir_BEFOREItemRandoEarlyKanto::
	db
.ckir_AFTERItemRandoEarlyKanto::
ItemRandoEasyTinTower::
.ckir_BEFOREItemRandoEasyTinTower::
	db
.ckir_AFTERItemRandoEasyTinTower::
ItemRandoDataEnd::
