ItemRandoData::
ItemRandoDataVersion::
	db 1
ItemRandoActive::
.ckir_BEFOREItemRandoActive::
	db
.ckir_AFTERItemRandoActive::
HoOhChamberNerfed::
.ckir_BEFOREHoOhChamberNerfed::
	db 
.ckir_AFTERHoOhChamberNerfed::
ClassicRainbowWing::
.ckir_BEFOREClassicRainbowWing::
	db 1
.ckir_AFTERClassicRainbowWing::
ItemRandoRocketless::
.ckir_BEFOREItemRandoRocketless::
	db
.ckir_AFTERItemRandoRocketless::
ItemRandoEasyClairBadge::
.ckir_BEFOREItemRandoEasyClairBadge::
	db
.ckir_AFTERItemRandoEasyClairBadge::
ItemRandoEarlyKanto::
.ckir_BEFOREItemRandoEarlyKanto::
	db
.ckir_AFTERItemRandoEarlyKanto::
ItemRandoEasyTinTower::
.ckir_BEFOREItemRandoEasyTinTower::
	db
.ckir_AFTERItemRandoEasyTinTower::
ItemRandoDataEnd::
